### ISSUE TITLE
Multisig. UI issues. Create ms flow

### ISSUE THREAD

**Issue by leohar** [novasamatech/nova-spektr#2531] opened 2024-10-23 12:19 UTC
### 1. Create ms popup
![Image](https://github.com/user-attachments/assets/bc77138b-6ee2-4797-beeb-f2e64a4d7c0e)

[Layouts reference](https://www.figma.com/design/HgFuj8QZd0xqEbkG10DIfs/Flexible-multisig-%7C-Milestone-4?node-id=369-58126&t=bKjB2kBmhRjZrNaX-1)

1. align to one line and update text of description 
2. Close button state of is hover on initial screen enter
3. update placeholder text: "Choose wallet name" -> "Enter name"
4. update text
5. add Back button
6. skeleton place is shifted close to Continue
7. "Additional costs" -> "Additional cost"

### 2. Create ms on the network popup
![Image](https://github.com/user-attachments/assets/60f69b88-015e-423a-a673-7b320fc2af1f)

[Layouts reference](https://www.figma.com/design/HgFuj8QZd0xqEbkG10DIfs/Flexible-multisig-%7C-Milestone-4?node-id=369-58363&t=bKjB2kBmhRjZrNaX-1)

1. NO NEED TO FIX (update popup title)
2. align and update description text
3. Label: Name -> Signatory name
4. Label: Your account -> Address
5. update placeholder text
6. plus button is wrong color
7. update placeholder text: Select threshold -> Select number
8. maybe disable threshold dropdown when <2 signatories inserted ???
9. update text
10. shifted skeleton place
11. Continue button is active anytime

### 3. Create ms editing fields
![Image](https://github.com/user-attachments/assets/8f33d8c4-0a01-47d2-a693-9354b72df219)

[Layouts reference](https://www.figma.com/design/HgFuj8QZd0xqEbkG10DIfs/Flexible-multisig-%7C-Milestone-4?node-id=1105-46243&t=bKjB2kBmhRjZrNaX-1)

1. when input address: inserted name is replaced with placeholder, name field is not editable
2. too big remove icon
3. shifted skeleton place

### 4. Confirm ms popup

![Image](https://github.com/user-attachments/assets/1c0f8fd9-8318-4f3b-97ca-d7440e4fcf4d)

[Layouts reference](https://www.figma.com/design/HgFuj8QZd0xqEbkG10DIfs/Flexible-multisig-%7C-Milestone-4?node-id=976-125596&t=bKjB2kBmhRjZrNaX-1)

1. close button is in hover state
2. no address under the name

### 5. Wallet details

- Singlechain multisig looks like this, which is not according to layout: network should be in the title with threshold info, there are two tabs: "Account and signatories" and "Delegated authorities"

![Image](https://github.com/user-attachments/assets/c0165f84-6e21-42e5-a958-71fb1c5fd5a4)

[Layouts reference](https://www.figma.com/design/HgFuj8QZd0xqEbkG10DIfs/Flexible-multisig-%7C-Milestone-4?node-id=383-77731&t=GP7uXMP5hmNOy6f7-1)

- Multichain multisig looks like this, also not according the layout: all multisig wallets are separate in each network, so in network 	 only one network is possible

![Image](https://github.com/user-attachments/assets/405342b5-301c-4424-93ae-02e92efec1b5)
![Image](https://github.com/user-attachments/assets/e9ab193f-6479-45b7-bb7d-a8ef0c0cdd61)

[Layouts reference](https://www.figma.com/design/HgFuj8QZd0xqEbkG10DIfs/Flexible-multisig-%7C-Milestone-4?node-id=907-52209&t=V2B6hpWHF4LJPQL4-1)

![Image](https://github.com/user-attachments/assets/b0c9150b-e267-4e79-890e-b82db3bb838a)
![Image](https://github.com/user-attachments/assets/0ab64625-a6a0-43e0-81f4-068fab0e1431)
![Image](https://github.com/user-attachments/assets/d4addda4-bddf-447d-9b44-54eac54cde37)

1. function button is in hover state
2. Remove treshold info, "Your accounts 1" -> "Account"
3. Contacts -> Signatories
4. Wallet name should be near Signatory address

### 6. Operations

![Image](https://github.com/user-attachments/assets/a8fbedc0-d7ef-43d4-9c56-c4f7d40599fb)

[Layouts reference](https://www.figma.com/design/HgFuj8QZd0xqEbkG10DIfs/Flexible-multisig-%7C-Milestone-4?node-id=445-31031&t=nNUCyVpyhtqd8KiY-1)

1. wrong icon
2. missing dialog icon
3. missing Sender
4. Call Hash -> Call hash
5. Call Data -> Call data
6. missing i icon

**Comment by Tbaut** [comment] 2024-10-28 11:32
### 1. Create ms popup

1. ok
2. ok
3. ok
4. Not OK, this description is erroneously talking about flexible multisigs. I'll adapt.
5. Not OK I don't think it makes sense since the "continue" and "back" buttons are for the flow. There's no "back" in that case bc we're at the first step. The close button/ click outside are the ways to close the modal
6. I don't understand the comment
7. ok

### 2. Create ms on the network popup
1. ok
2. ok
3. ok
4. Not OK, we expect the user to have their own account here, and that's what they can select. This has been discussed in the past and matches with what Gnosis Safe does.
 5. ok
 6. ok
 7. Not ok, we should name it threshold, because it is this. We don't say "Entre string" for the name input.
 8. There are many things we can do, I don't think disabling helps understand better
 9. ok
 10. I don't understand the comment
 11. Not ok, this is by design, and has been discussed in the past, we only show errors when the "continue" button has been pressed. 
 
###  3. Create ms editing fields
1. ok
2. ok
3. I don't understand the comment

### 4. Confirm ms popup
1. ok
2. ok

### 5. Wallet details
This is not part of the what I built and has been there since the get got

### 6. Operations
This is not part of the what I built and has been there since the get got

**Comment by Tbaut** [comment] 2024-10-28 11:51
BTW @pgolovkin and @leohar you're looking at mocks that have been updated. These mention "Flexible Multisig" whereas we're in the normal multisig flow, some text are therefore not adequate. I'll adapt.

**Comment by pgolovkin** [comment] 2024-10-28 11:55
@Tbaut my comments.


### 1. Create ms popup
5. It's ok and we have the same button right now. It was put on mockups and should be on developed layout.
6. The shimmered fee is too close to Continue button

### 2. Create ms on the network popup
4. The user has to select 1 own account and a few not own accounts. How it may be handled in this case? Address is more general wording that match better. That's why it's in mockups.
7. Agree
8. Agree
10. Same as `1.6`
11. Let's not fix it for now

### 3. Create ms editing fields
3. Same as `1.6`

### 5. Wallet details
Wallet details is a part of multisig feature. How much will it take to complete this task?

### 6. Operations
ok

**Comment by pgolovkin** [comment] 2024-10-29 07:03
> BTW @pgolovkin and @leohar you're looking at mocks that have been updated. These mention "Flexible Multisig" whereas we're in the normal multisig flow, some text are therefore not adequate. I'll adapt.

@Tbaut we're looking to correct mockups. Flexible multisig is a big feature that was splitted to 2 smaller features:
1. Remove matrix from Multisig and create mulsisig with system_remark
2. Create flexible multisig with pure proxy.

Mockups for this big feature is on a single page. The user flow for crating multisig without pure proxy is here https://www.figma.com/design/HgFuj8QZd0xqEbkG10DIfs/Flexible-multisig-%7C-Milestone-4?node-id=815-41264&t=FuIDHhd8XbFcdXkV-4

So the mockup that is used as a reference is correct.

**Comment by leohar** [comment] 2024-10-29 13:44
Status verification: 

What has been verified:

Create ms popup
  1. ❌ [text is not updated](https://www.figma.com/design/HgFuj8QZd0xqEbkG10DIfs/Flexible-multisig-%7C-Milestone-4?node-id=815-33382&t=FFP4VkRcEFW363ty-1)
  2. ✅ 
  3. ✅ 
  4. ❌ [text is not updated: flexible multisig mention](https://www.figma.com/design/HgFuj8QZd0xqEbkG10DIfs/Flexible-multisig-%7C-Milestone-4?node-id=815-33382&t=FFP4VkRcEFW363ty-1)
  5. ❌ no button added
  6. ✅ 
  7. ✅ 


Create ms on the network popup
  1. ✅ 
  2. ❌ [text is not updated, flexible ms mention](https://www.figma.com/design/HgFuj8QZd0xqEbkG10DIfs/Flexible-multisig-%7C-Milestone-4?node-id=815-41410&t=FFP4VkRcEFW363ty-1)
  3. ✅ 
  4. ✅ 
  5. ✅ 
  6. ✅ 
  7. ✅ 
  8. ✅ 
  9. ✅ 
  10. ✅ 
  11. ✅ 

Create ms editing fields
  1. ❌ when both signatories are in the wallet - input address for signatory name will be replaced with placeholder
  2. ✅ 
  3. ✅ 

Confirm ms popup
  1. ✅ 
  2. ✅ 

Wallet details 
- not yet decided what we will do with this? @pgolovkin 

Operations
- maybe reassign this? @pgolovkin

**Comment by pgolovkin** [comment] 2024-10-29 13:52
@leohar thanks. I'll re-assign it.

**Wallet details** will be created as a separate task 
**Operations** will be changed in terms of Flexible multisig feature.

**Comment by Tbaut** [comment] 2024-10-29 14:09
taking a look at the feedback now

**Comment by Tbaut** [comment] 2024-10-29 15:06
Thanks for the thorough review @leohar. Can I ask you for a review before the devs, so that I can fix anything that would be missing right away? -> https://github.com/novasamatech/nova-spektr/pull/2551

We should be complete now.

**Closed as completed** 2024-11-01 08:56 UTC
Labels: Bug

**Comment by leohar** [comment] 2024-11-05 15:03
Status verification: ✅
